name: Simple Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.7'  # Change to your preferred version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter papermill

      - name: Set Google API Key from GitHub Secrets
        run: echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> $GITHUB_ENV

       - name: Run Jupyter notebook
        run: |
          jupyter nbconvert --to notebook --execute script.ipynb